/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as CheckInsRouteImport } from './routes/checkIns'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MembersIndexRouteImport } from './routes/members/index'
import { Route as MembersMemberIdRouteImport } from './routes/members/$memberId'

const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInsRoute = CheckInsRouteImport.update({
  id: '/checkIns',
  path: '/checkIns',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersIndexRoute = MembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersMemberIdRoute = MembersMemberIdRouteImport.update({
  id: '/members/$memberId',
  path: '/members/$memberId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkIns': typeof CheckInsRoute
  '/plans': typeof PlansRoute
  '/members/$memberId': typeof MembersMemberIdRoute
  '/members/': typeof MembersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkIns': typeof CheckInsRoute
  '/plans': typeof PlansRoute
  '/members/$memberId': typeof MembersMemberIdRoute
  '/members': typeof MembersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkIns': typeof CheckInsRoute
  '/plans': typeof PlansRoute
  '/members/$memberId': typeof MembersMemberIdRoute
  '/members/': typeof MembersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/checkIns' | '/plans' | '/members/$memberId' | '/members/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/checkIns' | '/plans' | '/members/$memberId' | '/members'
  id:
    | '__root__'
    | '/'
    | '/checkIns'
    | '/plans'
    | '/members/$memberId'
    | '/members/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckInsRoute: typeof CheckInsRoute
  PlansRoute: typeof PlansRoute
  MembersMemberIdRoute: typeof MembersMemberIdRoute
  MembersIndexRoute: typeof MembersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkIns': {
      id: '/checkIns'
      path: '/checkIns'
      fullPath: '/checkIns'
      preLoaderRoute: typeof CheckInsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/': {
      id: '/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof MembersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/$memberId': {
      id: '/members/$memberId'
      path: '/members/$memberId'
      fullPath: '/members/$memberId'
      preLoaderRoute: typeof MembersMemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckInsRoute: CheckInsRoute,
  PlansRoute: PlansRoute,
  MembersMemberIdRoute: MembersMemberIdRoute,
  MembersIndexRoute: MembersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
